safe: true   # gh-pages forces this; match it for local development.
lsi: false   # gh-pages forces this; match it for local development.
collections:
  patterns:   # Important! This means there must be a _patterns folder.
    output: true  # Important! Without this, jekyll won't make _site/patterns.
    layout: pattern

